SELECT * FROM customer;

-- Business Analysis Questions
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS Revenue FROM 
customer GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
from customer
WHERE discount_applied='Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS `Average Product Rating`
FROM customer
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS DECIMAL(10,2))) DESC
LIMIT 5;

-- Q4. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS Revenue_Contribution 
FROM customer
group by age_group
ORDER BY Revenue_Contribution DESC;

-- Q5. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as Repeat_Buyers
from customer
WHERE previous_purchases>5
GROUP BY subscription_status;

-- Q6. What are the top 3 most purchased products within each category? 
with item_count as(
select category, item_purchased, COUNT(customer_id) as Total_Orders,
ROW_NUMBER() OVER(Partition By category order by COUNT(customer_id) DESC) AS Item_Rank FROM Customer
GROUP BY category,item_purchased )
SELECT Item_Rank, category, item_purchased, Total_Orders
FROM item_count
WHERE Item_Rank <=3;

-- Q7. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as Average_purchase FROM customer
WHERE shipping_type IN("Standard", "Express")
GROUP BY shipping_type;















